### ISSUE TITLE
Align* Environment ohne \usepackage{amsmath} im Posterbeispiel

### ISSUE THREAD

**Issue by Waldehyd** [Patschke/RPTU-Design#2]
Hi,

Danke für das Postertemplate! Kleine Anmerkung: Beim ersten kompilieren hat mein Compiler gemeckert dass \begin{align*} verwendet wird, das stammt wohl aus amsmath und ist im Posterbeispiel nicht eingebunden.

**Comment by Patschke** [comment]
Danke für dir Rückmeldung! Ich vermute, du hast mit `pdflatex` kompiliert? Das Template ist für `XeLaTeX`/`LuaLaTeX` gedacht, damit per `fontspec`/`unicode-math` RedHatText als Schrift geladen werden kann. Unter `pdflatex` eigene Schriften zu laden ist deutlich umständlicher.

Da ich absichtlich keine Fehler werfe, wenn mit `pdflatex` kompiliert wird (sondern dann halt einfach nur RedHatText nicht verwende), sollte ich aber natürlich dafür sorgen, dass auch das Beispiel direkt kompiliert ;-)

**Comment by Waldehyd** [comment]
Ah, das mit der Schriftart fiel mir noch gar nicht auf, Doku lesen will gelernt sein! Hab auf Lua umgestellt :D
